//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.AccessMaintenance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.AccessMaintenance.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ACC_FunctionCode, ACC_FunctionName, 
        ///SUBSTRING(ACC_FunctionName,0, len(ACC_FunctionName) - 13) as ModuleName,
        ///CASE 
        /// WHEN ACC_FunctionCode = &apos;AuditLogViewer&apos; THEN &apos;Log&apos; 
        /// WHEN  ACC_FunctionCode = &apos;SystemMaintenance&apos; THEN &apos;System&apos;
        /// WHEN  ACC_FunctionCode = &apos;AnnouncementMaintenance&apos; THEN &apos;Announcement&apos;
        /// WHEN  ACC_FunctionCode = &apos;OperatorMaintenance&apos; THEN &apos;Operator&apos;
        /// WHEN  ACC_FunctionCode = &apos;AccessMaintenance&apos; THEN &apos;Access&apos;
        /// WHEN ACC_FunctionCode = &apos;RejectedItemDecision&apos; THEN &apos;WebDecision&apos;
        /// WH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stmtGetAccessLevelModule {
            get {
                return ResourceManager.GetString("stmtGetAccessLevelModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ACC_FunctionCode ,ACC_FunctionName ,ACC_Group1 ,ACC_Group2 ,ACC_Group3 ,ACC_Group4 ,ACC_Group5 ,ACC_Group6 ,ACC_Group7 ,ACC_Group8 ,ACC_Group9 ,ACC_ParentFunction FROM dbo.TBL_ACCESSLEVEL with (nolock)
        ///WHERE ACC_ClientCode = @Client.
        /// </summary>
        internal static string stmtGetAll {
            get {
                return ResourceManager.GetString("stmtGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_ACCESSLEVEL SET {0} WHERE ACC_FunctionCode = @ModuleName AND ACC_ClientCode = @Client.
        /// </summary>
        internal static string stmtUpdateAccess {
            get {
                return ResourceManager.GetString("stmtUpdateAccess", resourceCulture);
            }
        }
    }
}
