//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.Announcement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.Announcement.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A.* FROM TBL_ANNOUNCEMENT (NOLOCK) A 
        ///WHERE A.ANM_CreatedBy IN (
        ///SELECT UST_UserID FROM TBL_OPERATOR (NOLOCK)
        ///WHERE UST_ForUnisys = @IsUnisys).
        /// </summary>
        internal static string stmtGetAllAnnouncement {
            get {
                return ResourceManager.GetString("stmtGetAllAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from TBL_ANNOUNCEMENT with(nolock) where ANM_ID = @ANMID.
        /// </summary>
        internal static string stmtGetAnnouncementByID {
            get {
                return ResourceManager.GetString("stmtGetAnnouncementByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_ANNOUNCEMENT WITH(NOLOCK) 
        ///WHERE (CONVERT (DATE, ANM_CreatedFrom) &lt;= CONVERT (DATE, GETDATE()))
        ///AND (CONVERT (DATE, GETDATE()) &lt;= CONVERT (DATE, ANM_CreatedTo)) 
        ///AND  ANM_Client IN (
        ///SELECT * FROM func_SplitDelimited(@ClientList,&apos;,&apos;))
        ///AND ANM_CreatedBy IN (
        ///SELECT UST_UserID FROM TBL_OPERATOR (NOLOCK)
        ///WHERE UST_ForUnisys = @IsUnisys).
        /// </summary>
        internal static string stmtGetAnnouncementToday {
            get {
                return ResourceManager.GetString("stmtGetAnnouncementToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TBL_ANNOUNCEMENT WHERE ANM_ID = @ID.
        /// </summary>
        internal static string stmtSQLDeleteAnnouncement {
            get {
                return ResourceManager.GetString("stmtSQLDeleteAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TBL_ANNOUNCEMENT
        ///           (ANM_Title
        ///           ,ANM_Description
        ///           ,ANM_CreatedFrom
        ///           ,ANM_CreatedTo
        ///           ,ANM_CreatedBy
        ///           ,ANM_Type,ANM_Client)
        ///     VALUES
        ///           (@Title
        ///           ,@Description
        ///           ,@CreatedFrom
        ///           ,@CreatedTo
        ///           ,@CreatedBy
        ///           ,@Type, @Client).
        /// </summary>
        internal static string stmtSQLInsertAnnouncement {
            get {
                return ResourceManager.GetString("stmtSQLInsertAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_ANNOUNCEMENT
        ///  SET ANM_Title = @Title
        ///      ,ANM_Description = @Description
        ///      ,ANM_Type = @Type
        ///      ,ANM_CreatedFrom = @CreatedFrom
        ///      ,ANM_CreatedTo = @CreatedTo, ANM_Client = @Client 
        /// WHERE ANM_ID = @ID.
        /// </summary>
        internal static string stmtSQLUpdAnnouncement {
            get {
                return ResourceManager.GetString("stmtSQLUpdAnnouncement", resourceCulture);
            }
        }
    }
}
