//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.ReportRepository {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.ReportRepository.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLPS_IFSPath.
        /// </summary>
        internal static string RlpsIFS {
            get {
                return ResourceManager.GetString("RlpsIFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ACC_Group{0} from TBL_ACCESSLEVEL nolock where ACC_FunctionCode = &apos;ViewAllBranch&apos;.
        /// </summary>
        internal static string stmtGetAccessAllBranch {
            get {
                return ResourceManager.GetString("stmtGetAccessAllBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetReportList.
        /// </summary>
        internal static string stmtGetAllReport {
            get {
                return ResourceManager.GetString("stmtGetAllReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;Data Source=&apos;+ LTRIM(RTRIM(CLT_ClientDBServerName)) + &apos;;Initial Catalog=&apos;+ LTRIM(RTRIM(CLT_ClientDBName)) +&apos;;Integrated Security=True&apos; as ConnString  FROM TBL_CLIENTINFO WITH(NOLOCK) where CLT_ClientCode =  @ClientCode.
        /// </summary>
        internal static string stmtGetClientConnectionString {
            get {
                return ResourceManager.GetString("stmtGetClientConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CLT_ClientCode ,CLT_ClientModule ,CLT_ClientName ,CLT_ClientAlias ,CLT_ClientDBName ,CLT_ClientDBServerName FROM TBL_CLIENTINFO(nolock).
        /// </summary>
        internal static string stmtGetClientInfoList {
            get {
                return ResourceManager.GetString("stmtGetClientInfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CLT_ClientCode ,CLT_ClientModule ,CLT_ClientName ,CLT_ClientAlias ,CLT_ClientDBName ,CLT_ClientDBServerName FROM TBL_CLIENTINFO(nolock)
        ///WHERE CLT_ClientCode &lt;&gt; &apos;Unisys&apos;.
        /// </summary>
        internal static string stmtGetClientInfoListExcUnisys {
            get {
                return ResourceManager.GetString("stmtGetClientInfoListExcUnisys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_AddDeleteUploadedRptFile.
        /// </summary>
        internal static string stmtSQLDeleteUploadedReport {
            get {
                return ResourceManager.GetString("stmtSQLDeleteUploadedReport", resourceCulture);
            }
        }
    }
}
