//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPC.Web.Collections {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPC.Web.Collections.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_BANK .
        /// </summary>
        internal static string GetBankSql {
            get {
                return ResourceManager.GetString("GetBankSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TRN_BranchNumber, TRN_BranchBSB  FROM TBL_TRANSBRANCH.
        /// </summary>
        internal static string GetBSBCtrlSql {
            get {
                return ResourceManager.GetString("GetBSBCtrlSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_COMMISSION.
        /// </summary>
        internal static string GetCommissionSql {
            get {
                return ResourceManager.GetString("GetCommissionSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM tbl_sitename WHERE SNT_ClientCode = @ClientCode.
        /// </summary>
        internal static string GetCPSClientSiteSql {
            get {
                return ResourceManager.GetString("GetCPSClientSiteSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_HOLIDAY.
        /// </summary>
        internal static string GetHolidaySql {
            get {
                return ResourceManager.GetString("GetHolidaySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select UST_Clients from TBL_Operator where UST_UserID = @userID.
        /// </summary>
        internal static string GetSelectedClientSql {
            get {
                return ResourceManager.GetString("GetSelectedClientSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_SITE.
        /// </summary>
        internal static string GetSiteSql {
            get {
                return ResourceManager.GetString("GetSiteSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_STATEHOLIDAY.
        /// </summary>
        internal static string GetStateHolidaySql {
            get {
                return ResourceManager.GetString("GetStateHolidaySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ACC_Group{0} FROM TBL_ACCESSLEVEL WHERE ACC_FunctionCode = @FunctionCode.
        /// </summary>
        internal static string GetUserRightsSql {
            get {
                return ResourceManager.GetString("GetUserRightsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group must be between 1 and 9 inclusive..
        /// </summary>
        internal static string UserGroupOutOfRange {
            get {
                return ResourceManager.GetString("UserGroupOutOfRange", resourceCulture);
            }
        }
    }
}
