//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.Dashboard.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT APP_MINAMT,APP_MAXAMT  FROM TBL_APPROVAL_AMTRANGE WHERE APP_CLIENTBANK = @ClientBank AND APP_REQUIREAPPROVAL = 1.
        /// </summary>
        internal static string sqlStmtGetAppApprove {
            get {
                return ResourceManager.GetString("sqlStmtGetAppApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UST_UserID as ActiveUser, ISNULL(UST_LastLogin,GETDATE()) as LoginDT FROM TBL_OPERATOR (NOLOCK) 
        ///WHERE UST_NoSession = 1
        ///AND UST_ForUnisys = 0
        ///AND UST_Clients = @ClientCode.
        /// </summary>
        internal static string stmtSqlGetActiveUserLoginForClient {
            get {
                return ResourceManager.GetString("stmtSqlGetActiveUserLoginForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UST_UserID as ActiveUser, ISNULL(UST_LastLogin,GETDATE()) as LoginDT FROM TBL_OPERATOR (NOLOCK) 
        ///WHERE UST_NoSession = 1
        ///AND UST_ForUnisys = 1.
        /// </summary>
        internal static string stmtSqlGetActiveUserLoginForUnisys {
            get {
                return ResourceManager.GetString("stmtSqlGetActiveUserLoginForUnisys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetRejTransactionStatusForDashboard.
        /// </summary>
        internal static string stmtSqlGetAllRejTransaction {
            get {
                return ResourceManager.GetString("stmtSqlGetAllRejTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetNCFBranchesListing.
        /// </summary>
        internal static string stmtSqlGetNCFBranchesListing {
            get {
                return ResourceManager.GetString("stmtSqlGetNCFBranchesListing", resourceCulture);
            }
        }
    }
}
