//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPC.Web.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPC.Web.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_BUSDATE SET BDT_Active = &apos;False&apos; WHERE BDT_Active = &apos;True&apos;.
        /// </summary>
        public static string ClearActiveDateSql {
            get {
                return ResourceManager.GetString("ClearActiveDateSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM TBL_BUSDATE(NOLOCK) WHERE BDT_BusDate = @BusinessDate.
        /// </summary>
        public static string DoesDateExistSql {
            get {
                return ResourceManager.GetString("DoesDateExistSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM TBL_BUSDATE(NOLOCK) WHERE BDT_BusDate = @BusinessDate.
        /// </summary>
        public static string DoesParamExistSql {
            get {
                return ResourceManager.GetString("DoesParamExistSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT BDT_BusDate FROM TBL_BUSDATE(NOLOCK) WHERE BDT_Active = &apos;True&apos;.
        /// </summary>
        public static string GetActiveDateSql {
            get {
                return ResourceManager.GetString("GetActiveDateSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PAR_VALUE1 FROM TBL_PARAM(NOLOCK) WHERE PAR_ParamName = @ParamKey.
        /// </summary>
        public static string GetParamVal1Sql {
            get {
                return ResourceManager.GetString("GetParamVal1Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PAR_VALUE2 FROM TBL_PARAM(NOLOCK) WHERE PAR_ParamName = @ParamKey.
        /// </summary>
        public static string GetParamVal2Sql {
            get {
                return ResourceManager.GetString("GetParamVal2Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Count(1) as RecordCount 
        ///FROM TBL_ACCESSLEVEL (NOLOCK)
        ///WHERE ACC_Group{0} = 1
        ///AND ACC_FunctionCode like &apos;%&apos;+@ModuleName +&apos;%&apos;.
        /// </summary>
        public static string GetUserAccessRightModules {
            get {
                return ResourceManager.GetString("GetUserAccessRightModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UST_BranchCode FROM TBL_OPERATOR (NOLOCK)
        ///WHERE UST_UserID = @UserID.
        /// </summary>
        public static string GetUserConnectedBranch {
            get {
                return ResourceManager.GetString("GetUserConnectedBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UST_SiteBranchCode  FROM TBL_OPERATOR (NOLOCK)
        ///WHERE UST_UserID = @UserID.
        /// </summary>
        public static string GetUserConnectedSiteBranch {
            get {
                return ResourceManager.GetString("GetUserConnectedSiteBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 UST_BranchCode,UST_SiteBranchCode FROM TBL_OPERATOR (nolock) WHERE UST_UserID = @UserID.
        /// </summary>
        public static string GetUserConnectedSiteBranchAndBranchCode {
            get {
                return ResourceManager.GetString("GetUserConnectedSiteBranchAndBranchCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TBL_BusDate VALUES (@BusinessDate, &apos;False&apos;).
        /// </summary>
        public static string InsertInactiveDateSql {
            get {
                return ResourceManager.GetString("InsertInactiveDateSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01,CASH IN;02,SA WDL;04,SA/CA ENC;07,FGL MSOUT.
        /// </summary>
        public static string listTellerTotalDescToRecon {
            get {
                return ResourceManager.GetString("listTellerTotalDescToRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1},{2},{3},{4},{5},{6}.
        /// </summary>
        public static string LogEntryFormatString {
            get {
                return ResourceManager.GetString("LogEntryFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp,Severity,Caller,UserName,Message,Data,FormattedException.
        /// </summary>
        public static string LogEntryHeaderString {
            get {
                return ResourceManager.GetString("LogEntryHeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KL1.
        /// </summary>
        public static string MainSite {
            get {
                return ResourceManager.GetString("MainSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT BDT_BusDate FROM TBL_BUSDATE WHERE BDT_BusDate = @BusinessDate) BEGIN UPDATE TBL_BUSDATE SET BDT_Active = &apos;True&apos; WHERE BDT_BusDate = @BusinessDate END ELSE BEGIN INSERT INTO TBL_BusDate VALUES (@BusinessDate, &apos;True&apos;) END.
        /// </summary>
        public static string SetActiveDateSql {
            get {
                return ResourceManager.GetString("SetActiveDateSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select MIN(HLD_Date) from TBL_Holiday(nolock)
        ///where HLD_Date &gt; @BusinessDate.
        /// </summary>
        public static string sqlNextHolidayDate {
            get {
                return ResourceManager.GetString("sqlNextHolidayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_CREDITCARDBIN(NOLOCK)  WHERE CC_BinNo = @BinNo.
        /// </summary>
        public static string stmtGetCCBinForCDVChecking {
            get {
                return ResourceManager.GetString("stmtGetCCBinForCDVChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;Data Source=&apos;+ LTRIM(RTRIM(CLT_ClientDBServerName)) + &apos;;Initial Catalog=&apos;+ LTRIM(RTRIM(CLT_ClientDBName)) +&apos;;Integrated Security=True&apos; as ConnString  FROM TBL_CLIENTINFO WITH(NOLOCK) where CLT_ClientCode =  @ClientCode.
        /// </summary>
        public static string stmtGetClientConnectionString {
            get {
                return ResourceManager.GetString("stmtGetClientConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_SITEDB (nolock)  WHERE DB_Site = @SiteName AND DB_BANK = @Bank.
        /// </summary>
        public static string stmtGetSiteClientConnectionString {
            get {
                return ResourceManager.GetString("stmtGetSiteClientConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Temp.
        /// </summary>
        public static string TempDirectory {
            get {
                return ResourceManager.GetString("TempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_PARAM SET PAR_VALUE1 = @PAR_VALUE1, PAR_VALUE2 = @PAR_VALUE2 WHERE PAR_ParamName = @ParamKey.
        /// </summary>
        public static string UpdateParamVal {
            get {
                return ResourceManager.GetString("UpdateParamVal", resourceCulture);
            }
        }
    }
}
