//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.SystemMaintenance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.SystemMaintenance.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(PAR_ParamName) FROM TBL_PARAM WITH (NOLOCK).
        /// </summary>
        internal static string stmtGetAllParamCount {
            get {
                return ResourceManager.GetString("stmtGetAllParamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  CAST((ABS(CHECKSUM(NEWID())) % 1000000 + 1) as varchar(100)) as TMPID, PAR_ParamName,PAR_Value1,PAR_Value2,PAR_Comment FROM TBL_PARAM WITH (NOLOCK).
        /// </summary>
        internal static string stmtGetAllParameter {
            get {
                return ResourceManager.GetString("stmtGetAllParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT PAR_ParamName,PAR_Value1,PAR_Value2,PAR_Comment FROM TBL_PARAM WITH (NOLOCK) WHERE PAR_ParamName = @ParamName.
        /// </summary>
        internal static string stmtGetParameterInfo {
            get {
                return ResourceManager.GetString("stmtGetParameterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TBL_PARAM WHERE PAR_ParamName = @ParamName.
        /// </summary>
        internal static string stmtSQLDeleteParameter {
            get {
                return ResourceManager.GetString("stmtSQLDeleteParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TBL_PARAM (PAR_ParamName ,PAR_Value1 ,PAR_Value2 ,PAR_Comment) VALUES (@ParamName ,@ParValue1 ,@ParValue2 ,@Comments).
        /// </summary>
        internal static string stmtSQLInsertParameter {
            get {
                return ResourceManager.GetString("stmtSQLInsertParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_PARAM SET PAR_Value1 = @ParValue1 ,PAR_Value2 = @ParValue2 ,PAR_Comment = @Comments WHERE PAR_ParamName = @ParamName.
        /// </summary>
        internal static string stmtSQLUpdParameter {
            get {
                return ResourceManager.GetString("stmtSQLUpdParameter", resourceCulture);
            }
        }
    }
}
