//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.BatchMaintenance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.BatchMaintenance.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Date: {0}; Batch No: {1}; RL Trans No: {2}.
        /// </summary>
        internal static string msgTransMaintData {
            get {
                return ResourceManager.GetString("msgTransMaintData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction status reset to {0}..
        /// </summary>
        internal static string msgTransStatusChanged {
            get {
                return ResourceManager.GetString("msgTransStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetPresentingBranchList.
        /// </summary>
        internal static string sqlStmtGetBranchList {
            get {
                return ResourceManager.GetString("sqlStmtGetBranchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetRejectedTransactionForWeb.
        /// </summary>
        internal static string sqlStmtGetRejectedTransactionList {
            get {
                return ResourceManager.GetString("sqlStmtGetRejectedTransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM TBL_REJECTITEMSTATUS (Nolock) 
        ///WHERE REJ_STATUS = &apos;W&apos;
        ///AND REJ_BUSDATE = @Busdate
        ///AND REJ_BATCHNUM = @BatchNum
        ///AND REJ_TRANSNUM = @TransNum.
        /// </summary>
        internal static string sqlStmtGetResetItem {
            get {
                return ResourceManager.GetString("sqlStmtGetResetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  CASE WHEN A.REJ_REASON LIKE &apos;RL%&apos; THEN &apos;RL&apos; 
        ///		WHEN A.REJ_REASON LIKE &apos;DI%&apos; THEN &apos;DI&apos; 
        ///		WHEN A.REJ_REASON LIKE &apos;REJECT%&apos; THEN &apos;PV&apos; ELSE &apos;&apos; END AS REJ_CATEGORY, 
        ///		 B.ITM_BatchDirectory, A.REJ_BUSDATE, A.REJ_BATCHNUM, A.REJ_TRANSNUM, A.REJ_REJECTBY,
        ///A.REJ_REJECTTIME, A.REJ_SITECODE, A.REJ_REASON, A.REJ_ALLOWTOLERANCE,
        ///A.REJ_ALLOWBREAKDOWN, A.REJ_STATUS, B.ITM_FLD9 AS ITM_Fld10,CASE WHEN (len(rtrim(ltrim(B.ITM_ProcMode))) &gt; 1 and B.ITM_ProcMode = &apos;02&apos;) THEN &apos;M&apos;
        ///  WHEN (len(rtrim(ltrim(B.ITM_Pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlStmtGetSelectedRejTransactionList {
            get {
                return ResourceManager.GetString("sqlStmtGetSelectedRejTransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_REJECTITEMSTATUS
        ///  SET REJ_STATUS= &apos;W&apos;,REJ_ACTIONEDBY = &apos;&apos;, REJ_ACTIONEDTIME = NULL
        ///  WHERE REJ_BUSDATE = @CurBusDate and REJ_BATCHNUM = @BatchNum 
        ///  AND REJ_TRANSNUM = @TransNo  AND LTRIM(RTRIM(REJ_ACTIONEDBY)) = @OperID AND REJ_STATUS = &apos;I&apos;.
        /// </summary>
        internal static string sqlStmtResetTransactionStatus {
            get {
                return ResourceManager.GetString("sqlStmtResetTransactionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LTRIM(RTRIM(ISNULL(REJ_STATUS,&apos;&apos;))) AS REJ_STATUS 
        /// FROM TBL_REJECTITEMSTATUS(NOLOCK)
        ///WHERE REJ_BUSDATE = @Busdate
        ///AND REJ_BATCHNUM = @BatchNum 
        ///AND REJ_TRANSNUM = @TransNo
        ///AND REJ_NEW_BUNDLEID = @BundleID.
        /// </summary>
        internal static string stmtGetREJLatestStatus {
            get {
                return ResourceManager.GetString("stmtGetREJLatestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_REJECTITEMSTATUS  
        ///SET REJ_STATUS = &apos;W&apos;, REJ_ACTIONEDBY= &apos;&apos;,
        ///REJ_ACTIONEDTIME = NULL
        ///WHERE REJ_ACTIONEDBY = @OperID 
        ///AND REJ_STATUS = &apos;I&apos;.
        /// </summary>
        internal static string stmtResetTransUponLogout {
            get {
                return ResourceManager.GetString("stmtResetTransUponLogout", resourceCulture);
            }
        }
    }
}
