//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.OperatorMaintenance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.OperatorMaintenance.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TBL_OPERATOR WHERE UST_UserID = @UserID.
        /// </summary>
        internal static string stmtDeleteUser {
            get {
                return ResourceManager.GetString("stmtDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CAST((ABS(CHECKSUM(NEWID())) % 1000000 + 1) as varchar(100)) as TMPID, UST_UserID ,UST_UserName ,UST_UserGroup ,UST_PwdChgLastDate ,UST_PwdChgDaysValid ,UST_PwdPos ,UST_Pwd_0 ,UST_Pwd_1 ,UST_Pwd_2 ,UST_Pwd_3 ,UST_Pwd_4 ,UST_Pwd_5 ,UST_PwdChgRetryCnt ,UST_Comments ,UST_ForcePwdChg ,UST_NoSession ,UST_Clients ,UST_LastLogin ,UST_Locked FROM TBL_OPERATOR WITH (NOLOCK).
        /// </summary>
        internal static string stmtGetAllUser {
            get {
                return ResourceManager.GetString("stmtGetAllUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CAST((ABS(CHECKSUM(NEWID())) % 1000000 + 1) as varchar(100)) as TMPID,  UST_UserID ,UST_UserName ,UST_UserGroup ,UST_PwdChgLastDate ,UST_PwdChgDaysValid ,UST_PwdPos ,UST_Pwd_0 ,UST_Pwd_1 ,UST_Pwd_2 ,UST_Pwd_3 ,UST_Pwd_4 ,UST_Pwd_5 ,UST_PwdChgRetryCnt ,UST_Comments ,UST_ForcePwdChg ,UST_NoSession ,UST_Clients ,UST_LastLogin ,UST_Locked 
        ///FROM TBL_OPERATOR WITH (NOLOCK)
        ///WHERE UST_ForUnisys = 
        ///(
        ///SELECT UST_ForUnisys FROM TBL_OPERATOR (NOLOCK)
        ///WHERE UST_UserID = @userID
        ///).
        /// </summary>
        internal static string stmtGetAllUserTiedToAdmin {
            get {
                return ResourceManager.GetString("stmtGetAllUserTiedToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CLT_ClientCode ,CLT_ClientModule ,CLT_ClientName ,CLT_ClientAlias ,CLT_ClientDBName ,CLT_ClientDBServerName FROM TBL_CLIENTINFO(nolock).
        /// </summary>
        internal static string stmtGetClientInfoList {
            get {
                return ResourceManager.GetString("stmtGetClientInfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CLT_ClientCode ,CLT_ClientModule ,CLT_ClientName ,CLT_ClientAlias ,CLT_ClientDBName ,CLT_ClientDBServerName FROM TBL_CLIENTINFO(nolock)
        ///WHERE CLT_ClientCode &lt;&gt; &apos;Unisys&apos;.
        /// </summary>
        internal static string stmtGetClientInfoListExcUnisys {
            get {
                return ResourceManager.GetString("stmtGetClientInfoListExcUnisys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TBL_OPERATOR 
        ///(UST_UserID,UST_UserName,UST_UserGroup,UST_PwdChgDaysValid,UST_PwdPos,UST_Pwd_0, UST_Comments,
        /// UST_ForcePwdChg, UST_Clients,UST_NoSession,UST_Locked,UST_ForUnisys)
        ///  VALUES (@UserID, @UserName, @UserGroup, 30, 0, @Password, @Comments,
        ///   1, @Clients,0,0,@ForUnisys).
        /// </summary>
        internal static string stmtInsertUser {
            get {
                return ResourceManager.GetString("stmtInsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select UST_NoSession from TBL_OPERATOR with(nolock) where UST_UserID = @userID.
        /// </summary>
        internal static string stmtIsUsrLogin {
            get {
                return ResourceManager.GetString("stmtIsUsrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_OPERATOR SET
        /// UST_Pwd_{0} = @Password, 
        /// UST_PwdPos = @PassPos, 
        /// UST_PwdChgLastDate = GETDATE(), 
        ///UST_ForcePwdChg = 1 WHERE UST_UserID = @UserID.
        /// </summary>
        internal static string stmtUpdateOperPassword {
            get {
                return ResourceManager.GetString("stmtUpdateOperPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF((SELECT UST_Locked FROM TBL_OPERATOR WITH(NOLOCK) WHERE UST_UserID = @UserID) = 1 AND @IsLocked = 0)
        ///BEGIN
        ///UPDATE TBL_OPERATOR
        ///    SET UST_LastLogin = GETDATE()
        ///    WHERE UST_UserID = @UserID AND ISNULL(UST_LastLogin,&apos;1900-01-01&apos;) &lt;&gt; &apos;1900-01-01&apos;
        ///END
        ///
        ///UPDATE TBL_OPERATOR SET UST_UserName = @UserName,UST_UserGroup = @UserGroup  ,UST_Comments = @Comment
        ///   ,UST_Clients =@Clients ,UST_ForUnisys = @ForUnisys, UST_Locked = @IsLocked, UST_NoSession = @IsSession,
        ///   UST_ForcePwdChg = @ForcedPwdChanged, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stmtUpdateUser {
            get {
                return ResourceManager.GetString("stmtUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM TBL_OPERATOR (NOLOCK) WHERE UST_UserID = @UserID.
        /// </summary>
        internal static string stmtUsrExisted {
            get {
                return ResourceManager.GetString("stmtUsrExisted", resourceCulture);
            }
        }
    }
}
