//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.RejectedItemDecision {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.RejectedItemDecision.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items for Transaction No: {0} accepted.
        /// </summary>
        internal static string msgAcceptedItem {
            get {
                return ResourceManager.GetString("msgAcceptedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision For Item Level: Transaction {0} on Level:{1}  Decision:{2}.
        /// </summary>
        internal static string msgItemDecisionLevel {
            get {
                return ResourceManager.GetString("msgItemDecisionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction No. {0} Rejected.
        /// </summary>
        internal static string msgItemReject {
            get {
                return ResourceManager.GetString("msgItemReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Date: {0}; Batch No: {1}; RL Trans No: {2}.
        /// </summary>
        internal static string msgTransMaintData {
            get {
                return ResourceManager.GetString("msgTransMaintData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction status changed to {0}..
        /// </summary>
        internal static string msgTransStatusChanged {
            get {
                return ResourceManager.GetString("msgTransStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetRLItemsForWebDecision.
        /// </summary>
        internal static string sqlStmrGetRLItemDetail {
            get {
                return ResourceManager.GetString("sqlStmrGetRLItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM TBL_REJECTITEMSTATUS WITH(NOLOCK)
        ///where REJ_Busdate =@CurBusDate  
        ///and REJ_BATCHNUM = @BatchNum 
        ///and REJ_TRANSNUM = @TransNo 
        ///AND REJ_NEW_BUNDLEID = @NewBundleID 
        ///and REJ_STATUS IN (&apos;I&apos;,&apos;C&apos;) and REJ_ACTIONEDBY &lt;&gt; @OperID .
        /// </summary>
        internal static string sqlStmtCheckCompletedInUseTrans {
            get {
                return ResourceManager.GetString("sqlStmtCheckCompletedInUseTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_REJECTITEMSTATUS  SET REJ_STATUS= &apos;C&apos;,REJ_ACTIONEDBY = @OperID, REJ_ACTIONEDTIME = GETDATE(),
        /// REJ_DECISION = @RejDecision, REJ_REMARK = @Remark WHERE REJ_BUSDATE = @CurBusDate and REJ_BATCHNUM = @BatchNum 
        ///  AND REJ_TRANSNUM = @TransNo  AND REJ_ACTIONEDBY = @OperID AND REJ_STATUS = &apos;I&apos; AND REJ_NEW_BUNDLEID = @NewBundle .
        /// </summary>
        internal static string sqlStmtCompleteTranStatus {
            get {
                return ResourceManager.GetString("sqlStmtCompleteTranStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetPresentingBranchList.
        /// </summary>
        internal static string sqlStmtGetBranchList {
            get {
                return ResourceManager.GetString("sqlStmtGetBranchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A.DID_Desc, B.* FROM TBL_DIFormatDef (NOLOCK) A INNER JOIN TBL_DIFormatFld (NOLOCK) B ON (A.DID_Format = B.DIF_Format) WHERE A.DID_Format = @FormatNo.
        /// </summary>
        internal static string sqlStmtGetDIFormatDef {
            get {
                return ResourceManager.GetString("sqlStmtGetDIFormatDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT RTRIM(REPLACE(STR(IFS_TransportID, 2), SPACE(1), &apos;0&apos;)) AS IFS_TransportID,  
        ///IFS_Site,IFS_SiteFolderName,IFS_IISVirtualPath, (IFS_IISVirtualPath+&apos;\&apos;+IFS_SiteFolderName) AS IFS_IISFullPath
        ///FROM TBL_TRANSPORT_IFSPATH (NOLOCK) WHERE IFS_TransportID = @TransportID AND IFS_Site = @Site.
        /// </summary>
        internal static string sqlStmtGetIISVirDirForIFSPath {
            get {
                return ResourceManager.GetString("sqlStmtGetIISVirDirForIFSPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT MAX(ITM_DIN) FROM TBL_ITEM WHERE ITM_BusDate = @Busdate AND ITM_BatchNum = @BatchNum AND ITM_BatchDirectory = @BatchDir.
        /// </summary>
        internal static string sqlStmtGetMaxDinNo {
            get {
                return ResourceManager.GetString("sqlStmtGetMaxDinNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT top 1 ITM_FLD12 FROM TBL_ITEM (NOLOCK) WHERE ITM_BusDate = @Busdate AND ITM_BatchDirectory = @BatchDir AND ITM_BatchNum = @BatchNum AND ITM_DIN &lt;&gt; @Din AND ITM_ItemType = &apos;S&apos;.
        /// </summary>
        internal static string sqlStmtGetOtherStubAcctNo {
            get {
                return ResourceManager.GetString("sqlStmtGetOtherStubAcctNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetPVDIItemsForWebDecision.
        /// </summary>
        internal static string sqlStmtGetPVItemDetail {
            get {
                return ResourceManager.GetString("sqlStmtGetPVItemDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetRejectedTransactionForWeb.
        /// </summary>
        internal static string sqlStmtGetRejectedTransactionList {
            get {
                return ResourceManager.GetString("sqlStmtGetRejectedTransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM TBL_REJECTITEMSTATUS (Nolock) 
        ///WHERE REJ_STATUS = &apos;W&apos;
        ///AND REJ_BUSDATE = @Busdate
        ///AND REJ_BATCHNUM = @BatchNum
        ///AND REJ_TRANSNUM = @TransNum
        ///AND REJ_NEW_BUNDLEID = @NewBundleID.
        /// </summary>
        internal static string sqlStmtGetResetItem {
            get {
                return ResourceManager.GetString("sqlStmtGetResetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  CASE WHEN A.REJ_REASON LIKE &apos;RL%&apos; THEN &apos;RL&apos; 
        ///		WHEN A.REJ_REASON LIKE &apos;DI%&apos; THEN &apos;DI&apos; 
        ///		WHEN A.REJ_REASON LIKE &apos;REJECT%&apos; THEN &apos;PV&apos; ELSE &apos;&apos; END AS REJ_CATEGORY, 
        ///		 B.ITM_BatchDirectory, A.REJ_BUSDATE, A.REJ_BATCHNUM, A.REJ_TRANSNUM, A.REJ_REJECTBY,
        ///A.REJ_REJECTTIME, A.REJ_SITECODE, A.REJ_REASON, A.REJ_ALLOWTOLERANCE,
        ///A.REJ_ALLOWBREAKDOWN, A.REJ_STATUS, B.ITM_Fld10,
        ///  CASE WHEN (len(rtrim(ltrim(B.ITM_ProcMode))) &gt; 1 and B.ITM_ProcMode = &apos;02&apos;) THEN &apos;M&apos;
        ///  WHEN (len(rtrim(ltrim(B.ITM_ProcMode))) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlStmtGetSelectedRejTransactionList {
            get {
                return ResourceManager.GetString("sqlStmtGetSelectedRejTransactionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_AddStubItemForWebDecision.
        /// </summary>
        internal static string sqlStmtInsNewStubItem {
            get {
                return ResourceManager.GetString("sqlStmtInsNewStubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_REJECTITEMSTATUS
        ///  SET REJ_STATUS= &apos;W&apos;,REJ_ACTIONEDBY = &apos;&apos;, REJ_ACTIONEDTIME = NULL
        ///  WHERE REJ_BUSDATE = @CurBusDate and REJ_BATCHNUM = @BatchNum 
        ///  AND REJ_TRANSNUM = @TransNo  AND REJ_ACTIONEDBY = @OperID AND REJ_STATUS = &apos;I&apos;
        ///  AND REJ_NEW_BUNDLEID = @BundleID.
        /// </summary>
        internal static string sqlStmtResetTransactionStatus {
            get {
                return ResourceManager.GetString("sqlStmtResetTransactionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_UpdAcceptedRejTransForWeb.
        /// </summary>
        internal static string sqlStmtUpdAcceptedTrans {
            get {
                return ResourceManager.GetString("sqlStmtUpdAcceptedTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_UpdAcceptedRejTransForWebRLOnly.
        /// </summary>
        internal static string sqlStmtUpdAcceptedTransRLOnly {
            get {
                return ResourceManager.GetString("sqlStmtUpdAcceptedTransRLOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_UpdateMultiLevelDecisionForWeb.
        /// </summary>
        internal static string sqlStmtUpdMultiLevelDecision {
            get {
                return ResourceManager.GetString("sqlStmtUpdMultiLevelDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_ITEM SET ITM_ReferToWeb = 0 WHERE ITM_BusDate = @Busdate 
        ///			AND ITM_BatchDirectory = @BatchDir 
        ///			AND ITM_BatchNum = @BatchNo AND ITM_TransNum = @TransNo.
        /// </summary>
        internal static string sqlStmtUpdRejectRLItems {
            get {
                return ResourceManager.GetString("sqlStmtUpdRejectRLItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_ITEM SET ITM_FLD12 = @UpdAcctNo, ITM_OriDepositor = ITM_Fld12,
        ///ITM_OriChqBSB = CASE WHEN (ITM_ItemType = &apos;C&apos;) THEN ITM_FLD4 ELSE ITM_OriChqBSB  END, ITM_FLD4 = @UpdBSB, ITM_TransSeqNum = @TranSeqNo, 
        ///ITM_FLD7 = CASE WHEN (ITM_ItemType = &apos;C&apos; and (LTRIM(RTRIM(ITM_FLD4)) &lt;&gt; LTRIM(RTRIM(@UpdBSB)))) THEN &apos;5&apos; ELSE ITM_FLD7 END,
        ///ITM_Amount = @UpdAmount
        ///			WHERE ITM_BusDate = @BusDate
        ///			AND ITM_BatchDirectory = @BatchDir
        ///			AND ITM_BatchNum = @BatchNum
        ///			AND ITM_TransNum = @TransID
        ///			AND ITM_D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sqlStmtUpdRLAmendedItem {
            get {
                return ResourceManager.GetString("sqlStmtUpdRLAmendedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_REJECTITEMSTATUS 
        ///SET REJ_STATUS = @status, REJ_ACTIONEDBY =  @OperID , REJ_ACTIONEDTIME = GETDATE() 
        ///where REJ_Busdate = @CurBusDate 
        /// and REJ_BATCHNUM = @BatchNum 
        ///and REJ_TRANSNUM = @TransNo 
        ///AND REJ_NEW_BUNDLEID = @BundleID 
        ///AND (REJ_ACTIONEDBY = @OperID OR ((REJ_STATUS = &apos;W&apos;) 
        ///AND (@status = &apos;I&apos;))).
        /// </summary>
        internal static string sqlStmtUpdTransactionStatus {
            get {
                return ResourceManager.GetString("sqlStmtUpdTransactionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Date = {0}; BatchNo = {1}; BatchDir = {2}; Trans No = {3}.
        /// </summary>
        internal static string strLogTransactionDetails {
            get {
                return ResourceManager.GetString("strLogTransactionDetails", resourceCulture);
            }
        }
    }
}
