//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.AuditLogViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.AuditLogViewer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LogID ,[Timestamp] ,Severity ,[Caller] ,ClientCode ,UserName ,[Message] ,Data ,Exception FROM TBL_LOG WITH(NOLOCK).
        /// </summary>
        internal static string stmtGetAllAuditLog {
            get {
                return ResourceManager.GetString("stmtGetAllAuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  LogID ,[Timestamp] ,Severity ,[Caller] ,ClientCode ,UserName ,[Message] ,Data ,Exception FROM TBL_LOG WITH(NOLOCK) where TimeStamp&gt;=@startDateTime AND TimeStamp &lt;=@endDateTime.
        /// </summary>
        internal static string stmtGetAllAuditLogFilter {
            get {
                return ResourceManager.GetString("stmtGetAllAuditLogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(LogID) FROM TBL_LOG WITH (NOLOCK).
        /// </summary>
        internal static string stmtGetAllParamCount {
            get {
                return ResourceManager.GetString("stmtGetAllParamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT LogID ,[Timestamp] ,Severity ,[Caller] ,ClientCode ,UserName ,[Message] ,Data ,Exception FROM TBL_LOG WITH(NOLOG) WHERE LogID = @LogID.
        /// </summary>
        internal static string stmtGetAuditLogInfo {
            get {
                return ResourceManager.GetString("stmtGetAuditLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;ALL&apos; CLT_ClientCode,&apos;&apos; CLT_ClientModule,&apos;&apos; CLT_ClientName,&apos;&apos; CLT_ClientAlias,&apos;&apos; CLT_ClientDBName,&apos;&apos; CLT_ClientDBServerName 
        ///UNION ALL SELECT CLT_ClientCode ,CLT_ClientModule ,CLT_ClientName ,CLT_ClientAlias ,CLT_ClientDBName ,CLT_ClientDBServerName FROM TBL_CLIENTINFO(nolock).
        /// </summary>
        internal static string stmtGetClientInfoList {
            get {
                return ResourceManager.GetString("stmtGetClientInfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;ALL&apos; CLT_ClientCode,&apos;&apos; CLT_ClientModule,&apos;&apos; CLT_ClientName,&apos;&apos; CLT_ClientAlias,&apos;&apos; CLT_ClientDBName,&apos;&apos; CLT_ClientDBServerName 
        ///UNION ALL SELECT CLT_ClientCode ,CLT_ClientModule ,CLT_ClientName ,CLT_ClientAlias ,CLT_ClientDBName ,CLT_ClientDBServerName FROM TBL_CLIENTINFO(nolock)
        ///WHERE CLT_ClientCode &lt;&gt; &apos;Unisys&apos;.
        /// </summary>
        internal static string stmtGetClientInfoListExcUnisys {
            get {
                return ResourceManager.GetString("stmtGetClientInfoListExcUnisys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A.RPT_ReportCode,A.RPT_ReportDesc, A.RPT_ReportName, A.RPT_ReportSrc, @@SERVERNAME AS RPT_WebServerName, &apos;UVRPSWeb&apos; AS RPT_WebDBName, 
        ///A.RPT_ReportType FROM TBL_REPORT A WITH (NOLOCK) WHERE A.RPT_ReportCode = @ReportCode and A.RPT_ClientCode = &apos;ALL&apos;.
        /// </summary>
        internal static string stmtGetPrintAuditReportInfo {
            get {
                return ResourceManager.GetString("stmtGetPrintAuditReportInfo", resourceCulture);
            }
        }
    }
}
