//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBPCWeb.Modules.OutlookRecipientMaintenance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UBPCWeb.Modules.OutlookRecipientMaintenance.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TBL_RECIPIENT WHERE Recp_ID = @Recp_ID.
        /// </summary>
        internal static string stmtDelOutlookRecipient {
            get {
                return ResourceManager.GetString("stmtDelOutlookRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM TBL_RECIPIENT WHERE Recp_ID &lt;&gt;@ID AND Recp_ClientCode = @ClientCode AND Recp_EmailAddr = @EmailAddr.
        /// </summary>
        internal static string stmtEmailAddrExist {
            get {
                return ResourceManager.GetString("stmtEmailAddrExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sp_GetAllRecipient.
        /// </summary>
        internal static string stmtGetAllRecipient {
            get {
                return ResourceManager.GetString("stmtGetAllRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_RECIPIENT WHERE Recp_ID =  @Recp_ID.
        /// </summary>
        internal static string stmtGetRecipient {
            get {
                return ResourceManager.GetString("stmtGetRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM TBL_RECIPIENT WHERE Recp_ClientCode = @ClientCode.
        /// </summary>
        internal static string stmtGetRecpByClient {
            get {
                return ResourceManager.GetString("stmtGetRecpByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TBL_RECIPIENT(Recp_ClientCode,Recp_EmailAddr,Recp_CreationDate,Recp_CreatedBy)
        ///VALUES(@Recp_ClientCode,@Recp_EmailAddr,@Recp_CreationDate,@Recp_CreatedBy).
        /// </summary>
        internal static string stmtInsOutlookRecipient {
            get {
                return ResourceManager.GetString("stmtInsOutlookRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TBL_RECIPIENT SET 
        ///Recp_ClientCode = @Recp_ClientCode,
        ///Recp_EmailAddr = @Recp_EmailAddr
        ///WHERE Recp_ID = @Recp_ID.
        /// </summary>
        internal static string stmtUpdOutlookRecipient {
            get {
                return ResourceManager.GetString("stmtUpdOutlookRecipient", resourceCulture);
            }
        }
    }
}
